export const elementsProvider = {
  SIDEBAR_OPTIONS_MODEL:'#sidebar_options_model',
  SIDEBAR_OPTIONS: '#sidebar_options',
  PATHS:'#ribbon_path',
  PATHSM1:'#ribbon_pathV1',
  PATHSM2:'#ribbon_pathV2',
  PARALLEL_SET_CONTAINER: '#parallel_set_container',
  PARALLEL_SET_CONTENT: '#parallel_set_content',
  CLUSTERED_BAR: '#clustered_bar',
  CLUSTERED_BAR_CONTAINER: '#clustered_bar_container',
  UPLOAD_CSV_BUTTON: '#upload_csv',
  UPLOAD_JSON_BUTTON: '#upload_json',
  UPLOAD_INPUT: '#upload_input',
  UPLOAD_PLACE_HOLDER: '#upload_placeholder',
  LOADER_SECTION: '#loader_section',
  OPEN_FAQ: '#open_faq',
  FAQ_MODAL: '#faq_modal',
  FILE_NAME: '#file_name',
  PATH_MODAL_1:'#pathModal1',
  PATH_MODAL_2:'#pathModal2',
  DONUT_CHART:'#donut_chart',
  MODEL_BAR:'#model_bar',
  COMPARISON: '#comparison',
  SELECTBUTTON: '#selectButton',
  OPTIONPROTECTED:  '#optionProtected',
  MODELS: '#models',
  FEATURES: '#features',
  CONTAINER: '#container',
  MODAL1_CONTENT: '#modal1-content',
  MODAL1: '#modal1',
  BUTTON1: '#button1',
  BUTTON2: '#button2',
  BUTTON3: '#button3',
  SPECIFICVIEW: '#SpecificView',
  PRECISION: '#precision'
}